name: Build & Deploy Blog to Pages
# 监听main分支推送代码
on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 拉取仓库全部代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 安装Ruby环境（Jekyll依赖Ruby）
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "3.2"

      # 3. 安装Jekyll所有依赖
      - name: Install dependencies
        run: bundle install

      # 4. 构建静态网页，输出到_site文件夹
      - name: Build static site
        run: bundle exec jekyll build --destination _site

      # 5. 部署静态文件到gh-pages分支
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site